-- Feature the curated subset of real companies that correspond to the
-- public marketing site's former hardcoded COS showcase array.
-- Only sets featured=1 on these 63 specific rows; touches no other data
-- in the existing companies table.
UPDATE companies SET featured = 1 WHERE id IN (2817,2552,1219,2356,3198,469,3095,2575,3054,350,849,848,973,1050,476,1060,831,1042,2736,2777,403,1085,3049,850,3222,2134,2272,164,54,2516,874,839,3324,3300,2850,2774,572,1033,636,1162,2886,3498,846,845,844,884,305,3329,2202,27,2526,2686,3124,3164,1155,1004,1003,618,883,1126,12,2569,1908);

-- Maps the old hardcoded COS ids (still referenced by RESP/PD/CANNED_RESULTS
-- in index.html) to the real companies table ids, and carries the demo-only
-- presentational fields (logo/color/score/caps/regions/sites/etc.) that have
-- no equivalent column in the real companies table -- these were always
-- illustrative showcase flourishes, not real data, so they're kept as-is
-- rather than invented fresh for the real dataset.
DROP TABLE IF EXISTS featured_id_map;
CREATE TABLE featured_id_map (
  cos_id INTEGER PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  type TEXT,
  logo TEXT,
  color TEXT,
  score INTEGER,
  alerts INTEGER DEFAULT 0,
  alert_url TEXT,
  alert_info TEXT,
  upd TEXT,
  partner_type TEXT,
  caps TEXT,
  regions TEXT,
  sites TEXT
);

INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (2,2817,'CDMO · Biologics','MB','#2d5a3d',91,0,NULL,NULL,'3 hours ago',NULL,'["mAbs & Bispecifics","ADCs & Bioconjugation","CHO Cell Line Development","Fusion Proteins & HPAPIs"]','["europe","italy","eu"]','["Pomezia, Rome, Italy"]'); -- Menarini Biotech -> Menarini Biotech
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (3,2552,'CDMO · Injectable Manufacturing','FP','#8B6914',88,1,'https://eudragmdp.ema.europa.eu/inspections/gmpc/searchGMPCompliance.do','Search EudraGMDP — EU GMP compliance database (EMA)','6 hours ago',NULL,'["Sterile Injectables","Suspensions & Nanoemulsions","Aseptic & Terminal Sterilisation","Formulation Development"]','["europe","italy","eu","asia","china"]','["Palomonte, Salerno, Italy","Hefei, China"]'); -- Fisiopharma -> Fisiopharma
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (4,1219,'CRO · CDMO · Clinical Services','AL','#1a4a6e',92,0,NULL,NULL,'2 hours ago',NULL,'["API & HPAPI Manufacture","Clinical Trial Manufacturing","Drug Discovery & Development","ADCs & Biologics"]','["europe","uk","united kingdom","northern ireland","ireland","usa","united states","america","global"]','["Craigavon, Northern Ireland, UK","Dundalk, Ireland","Audubon, Pennsylvania, USA","Lansdale, Pennsylvania, USA","Singapore"]'); -- Almac Group -> Almac Group
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (5,2356,'CDMO · Small Molecule API','CB','#3a1a4a',90,0,NULL,NULL,'5 hours ago',NULL,'["API & HPAPI Manufacture","Small Molecule Synthesis","High Potency Formulations","Controlled Substances"]','["usa","united states","america","europe","italy","sweden","uk","global"]','["Charles City, Iowa, USA","Tallinn, Estonia","Paullo, Milan, Italy","Karlskoga, Sweden","Tallinn, Estonia"]'); -- Cambrex Corporation -> Cambrex Corporation
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (6,3198,'CDMO · RNA & Advanced Biomolecules','SB','#1a4a3a',78,0,NULL,NULL,'Today',NULL,'["mRNA & RNA Manufacturing","Plasmid DNA Production","Lipid Nanoparticles (LNPs)","Cell & Gene Therapy"]','["usa","united states","america","houston","texas"]','["Houston, Texas, USA"]'); -- Soter Bio -> Soter Bio
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (7,469,'CDMO · Synthetic DNA & Gene Therapy','TL','#0a3a5a',89,0,NULL,NULL,'4 hours ago',NULL,'["dbDNA Enzymatic Synthesis","AAV & Viral Vector Supply","mRNA Starting Materials","Gene Editing & Cell Therapy"]','["europe","uk","united kingdom","england","global"]','["Hampton, Middlesex, UK"]'); -- Touchlight -> Touchlight
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (15,3095,'CDMO · Broad Dosage Form Specialist','RC','#1a5a3a',90,0,NULL,NULL,'2 hours ago',NULL,'["Inhalation, Inhaler & Nasal Delivery","Sterile Injectables & Fill-Finish","HPAPI & High Potency Manufacturing","Biologics, mRNA & Gene Therapy"]','["europe","sweden","uk","france","switzerland","eu","global"]','["Jordbro, Sweden","multiple sites: Sweden, France, UK, Switzerland"]'); -- Recipharm AB -> Recipharm AB
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (16,2575,'CRO · Antibody Discovery & Engineering','FA','#3a1a5a',86,0,NULL,NULL,'3 hours ago',NULL,'["Monoclonal Antibody Production","Antibody Humanisation & Engineering","Bispecific & Multispecific Antibodies","Antibody Sequencing & AI"]','["europe","uk","united kingdom","northern ireland","ireland","belfast","global"]','["Belfast, Northern Ireland, UK"]'); -- Fusion Antibodies -> Fusion Antibodies 
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (17,3054,'CDMO · Biologics, Gene Therapy & Advanced Therapies','PB','#1a3a5a',84,0,NULL,NULL,'4 hours ago',NULL,'["mRNA Vaccines & Protein Therapeutics","Viral Vectors & Cell/Gene Therapy","ADC & Biologics Development","Plasmid DNA & Cell Line Development"]','["usa","united states","america","new jersey","global"]','["Pennington, New Jersey, USA"]'); -- ProBio -> ProBio
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (18,350,'CRO · Drug Developability & Cell Line Development','CT','#2a4a1a',81,0,NULL,NULL,'5 hours ago',NULL,'["Drug Developability & Protein Engineering","Cell Line Development (CHO, HEK, others)","Bioprocess & Bioassay Development","Immuno-oncology & Cell Therapy"]','["usa","united states","america","california","san francisco","bay area","global"]','["Union City, California, USA"]'); -- Celltheon -> Celltheon
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (19,849,'TechBio · Cardiac Drug Discovery Platform','HB','#8B0025',85,0,NULL,NULL,'1 hour ago','seeker','["Cardioid iPSC Drug Discovery Platform","AI-Driven Cardiac Analytics","Heart Failure Co-development","Cardiomyopathy & Fibrosis Models"]','["europe","austria","eu","vienna","global"]','["Vienna Biocenter, Vienna, Austria"]'); -- Heartbeat.bio -> Heartbeat.bio
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (20,848,'TechBio · Non-Viral Gene Delivery Platform','BB','#2a1a5a',82,0,NULL,NULL,'2 hours ago','seeker','["Celletto™ Mechanoporation Platform","Non-Viral Gene Delivery","T-Cell Engineering & CAR-T","Gene Therapy & Cell Therapy"]','["usa","united states","america","california","riverside"]','["University of California, Riverside, California, USA"]'); -- Basilard BioTech -> Basilard BioTech
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (21,973,'Drug Delivery · ODT Platform Technology','IP','#1a5a1a',80,0,NULL,NULL,'3 hours ago','seeker','["InstaPill® ODT Platform — 3-10 Second Disintegration","Orally Disintegrating Tablet Technology","Registered in 50+ Countries","ODT Formulation Development & Licensing"]','["india","asia","global","bengaluru","karnataka"]','["Bengaluru, Karnataka, India"]'); -- InstaPill -> InstaPill
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (22,1050,'Pharma · Contract Manufacturing & Licensing','OR','#004B8D',87,0,NULL,NULL,'2 hours ago','both','["Cytotoxic API & Oncology Manufacturing","Dry Powder Inhaler (DPI) Technology","Solid Dose, Topicals & Veterinary","API Licensing & Out-licensing"]','["europe","finland","eu","nordic","scandinavia","global"]','["Espoo, Finland","Turku, Finland"]'); -- Orion Corporation -> Orion
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (23,476,'Specials & Unlicensed Medicines · Drug Delivery','VP','#4a1a5a',83,0,NULL,NULL,'2 hours ago',NULL,'["Pharmaceutical Specials & Unlicensed Medicines","Bespoke Drug Delivery Reformulation","Paediatric & Niche Patient Formulations","In-licensing & Regulatory Approval Pathway"]','["europe","uk","united kingdom","england","surrey","global"]','["Weybridge, Surrey, UK"]'); -- Veriton Pharma -> Veriton Pharma
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (24,1060,'TechBio · Smart Oncology Drug Delivery Platform','PN','#5a1a1a',79,0,NULL,NULL,'3 hours ago','seeker','["Smart Chemotherapy Drug Delivery Platform","Tumour-Targeted Bioconjugation","Oncology Combination Products","Chemotherapy Efficacy & Safety Enhancement"]','["usa","united states","america","michigan","ann arbor","global"]','["Ann Arbor, Michigan, USA"]'); -- Peptinovo Biopharma -> Peptinovo Biopharma
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (25,831,'TechBio · Biologics Platform Technology','AT','#0a4a6a',88,0,NULL,NULL,'2 hours ago','seeker','["Hybrozyme™ Hyaluronidase Subcutaneous Delivery","NexMab™ ADC Technology","NexP™ Long-Acting Protein Fusion","Biosimilars & Biobetter Pipeline"]','["asia","korea","south korea","daejeon","global"]','["Daejeon, South Korea"]'); -- Alteogen -> Alteogen
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (26,1042,'TechBio · Abuse-Deterrent Transdermal Drug Delivery','NB','#1a4a3a',82,0,NULL,NULL,'2 hours ago','seeker','["AVERSA™ Abuse-Deterrent Transdermal Technology","Opioid Patch Safety Platform","Transdermal Drug Delivery Systems","4P Therapeutics Clinical Development"]','["usa","united states","america","florida","orlando","global"]','["Orlando, Florida, USA"]'); -- Nutriband -> Nutriband
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (28,2736,'CDMO · Pulmonary, Transdermal, Sterile & Nasal','KD','#003366',93,0,NULL,NULL,'2 hours ago',NULL,'["MDI, DPI & Pulmonary Drug Delivery","Transdermal & Microneedle Systems","Sterile Injectable Fill-Finish","Nasal Spray & Intradermal Delivery"]','["usa","united states","america","minnesota","uk","united kingdom","global"]','["St. Paul, Minnesota, USA","UK sites"]'); -- Kindeva Drug Delivery -> Kindeva Drug Delivery
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (29,2777,'CDMO · Transdermal, Oral Thin Film & Advanced Drug Delivery','LT','#8B0025',94,0,NULL,NULL,'2 hours ago',NULL,'["Transdermal Patches & Wearable Devices","Oral Thin Films (OTF)","Microneedle Array Patches","Nasal & Sterile Drug Delivery Systems"]','["europe","germany","usa","israel","global"]','["Andernach, Germany","US sites","Israel site"]'); -- LTS Lohmann -> LTS Lohmann Therapie-Systeme AG
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (30,403,'CDMO · Transdermal Patch Development & Manufacturing','LP','#1a3a5a',84,0,NULL,NULL,'2 hours ago',NULL,'["Transdermal Patch Development","Self-Developed & Custom Patch Manufacturing","Low Oral Bioavailability Drug Delivery","Flexible Dose Patch Formulation"]','["europe","germany","eu","miesbach","china","global"]','["Miesbach, Germany"]'); -- Luye Pharma AG -> Luye Pharma AG
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (31,1085,'CDMO · Transdermal Patch Specialist','PS','#1a4a5a',85,0,NULL,NULL,'2 hours ago',NULL,'["High-Barrier Transdermal Patch Development","ANDA, NDA & 505(b)(2) TDD Systems","50M+ Annual Patch Manufacturing Capacity","End-to-End Formulation to Coating"]','["usa","united states","america","florida","miami"]','["Miami, Florida, USA"]'); -- ProSolus Pharmaceuticals -> Prosolus Pharmaceuticals
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (32,3049,'TechBio · Brain Drug Delivery Platform','PN','#2a1a6a',80,0,NULL,NULL,'2 hours ago','seeker','["CNS & Brain Drug Delivery Technology","Blood-Brain Barrier Solutions","Brain Tumour & Neurodegeneration Platform","Epilepsy, Stroke & Neuro Disease Targeting"]','["usa","united states","america","california","redwood"]','["Redwood, California, USA"]'); -- Precision NeuroMed -> Precision NeuroMed
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (33,850,'Biotech · Neurological Disease Drug Discovery','CP','#2a5a2a',78,0,NULL,NULL,'2 hours ago','seeker','["Neurological Disease Drug Discovery","mRNA & Oligonucleotide Therapeutics","Small Molecule CNS Drug Discovery","High-Throughput Screening Platform"]','["europe","denmark","eu","nordic","scandinavia","horsholm"]','["Hørsholm, Denmark"]'); -- Contera Pharma -> Contera Pharma
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (34,3222,'CDMO · Clinical-Stage Sterile Fill-Finish Specialist','SY','#2a3a6a',88,0,NULL,NULL,'2 hours ago',NULL,'["Aseptic Vial Fill-Finish (Liquid & Lyophilised)","Biologics, ADC & HPAPI Sterile Filling","Fast-Turnaround Phase I/II Clinical Supply","Small-Scale to Low-Volume Commercial"]','["europe","uk","united kingdom","scotland","stirling","global"]','["Stirling, Scotland, UK"]'); -- Symbiosis Pharmaceutical Services -> Symbiosis Pharmaceutical Services
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (35,2134,'CRO · Pharmaceutical Engineering & Equipment','3P','#3a2a6a',82,0,NULL,NULL,'2 hours ago',NULL,'["Fill & Finish Equipment Design","Containment & Automation Engineering","Cell & Gene Therapy Process Equipment","DPI & Inhalation Manufacturing Solutions"]','["europe","uk","united kingdom","england","warwick","warwickshire"]','["Warwick, UK"]'); -- 3P Innovation -> 3P innovation
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (36,2272,'CRO · iPSC Human Disease Modelling Platform','AB','#1a4a5a',83,0,NULL,NULL,'2 hours ago','seeker','["Human iPSC Disease Models (Neuro & Cardio)","Patient-Derived Cell-Based Assays","Drug Safety & Efficacy Evaluation","Neurodegenerative Disease Modelling"]','["europe","uk","scotland","edinburgh","global"]','["Edinburgh, Scotland, UK"]'); -- Axol Bioscience -> Axol Bioscience
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (37,164,'CDMO · Biologics, ADC & Bioconjugation Specialist','AZ','#2a1a4a',87,0,NULL,NULL,'2 hours ago',NULL,'["ADC & Bioconjugation Development & Manufacture","Antibody Discovery & Engineering","Biopharmaceutical Process Development","Cytotoxic Payload Synthesis & Linker Manufacture"]','["europe","uk","england","cambridge","usa","united states","global"]','["Cambridge, UK · USA"]'); -- Abzena -> Abzena Plc
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (42,54,'MedTech · Pulmonary Drug Delivery Technology','AG','#1a3a5a',88,0,NULL,NULL,'2 hours ago','both','["Vibrating Mesh Nebuliser Technology","Inhaled Drug Delivery for ICU & Emergency","Aerogen Solo & Ultra Platform","Drug-Device Combination Partnerships"]','["europe","ireland","galway","eu","global"]','["Galway, Ireland"]'); -- Aerogen -> Aerogen
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (46,2516,'CDMO · Clinical Trial Manufacturing & Supply','ER','#4a2a1a',82,0,NULL,NULL,'2 hours ago',NULL,'["End-to-End Clinical Trial Manufacturing","MHRA & HPRA Approved Facilities","QP Batch Certification & Release","Global Clinical Trial Distribution"]','["europe","uk","england","kent","sevenoaks","eu","ireland","global"]','["Sevenoaks, Kent, UK"]'); -- Eramol -> Eramol
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (47,874,'CDMO · Mesoporous Drug Delivery Platform','BR','#2a3a5a',79,0,NULL,NULL,'2 hours ago',NULL,'["Mesoporous Silica Drug Delivery Platform","Bioavailability Enhancement Technology","Nanoparticle & Microparticle Formulation","Pharmacokinetics Improvement CDMO"]','["europe","italy","eu","lonigo","vicenza"]','["Lonigo, Vicenza, Italy"]'); -- Brenta -> Brenta
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (48,839,'Biopharma · Oncology Pipeline & Licensing','AT','#4a1a2a',81,0,NULL,NULL,'2 hours ago','seeker','["First-in-Class Oncology Drug Discovery","ADC & Immuno-Oncology Pipeline","Asia-Pacific to Global Licensing","BMS/Celgene Strategic Partner"]','["china","asia","asia-pacific","shanghai","global","usa"]','["Shanghai, China · Global"]'); -- Antengene Corp -> Antengene Corp
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (50,3324,'CRDMO · ADC & Bioconjugate Specialist','WX','#1a2a4a',90,0,NULL,NULL,'2 hours ago',NULL,'["End-to-End ADC & Bioconjugate CRDMO","Drug Conjugate & Linker Development","Single-Source Open-Access ADC Platform","1000+ Global ADC Specialists"]','["china","global","asia","hong kong","europe","usa"]','["Global (HK Listed: 2268.HK)"]'); -- WuXi XDC -> WuXi XDC
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (52,3300,'CDMO · Specialty API & Complex Chemistry','VN','#2a4a3a',85,0,NULL,NULL,'2 hours ago',NULL,'["Specialty API Process Development & Manufacturing","HPAPI, Oligonucleotides & Peptides","ADC Payload & Drug Conjugate Chemistry","Particle Engineering & Solid State Research"]','["usa","united states","massachusetts","devens","europe","global"]','["Devens, Massachusetts, USA"]'); -- Veranova -> Veranova
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (53,2850,'CDMO · Biologics & Advanced Modalities','MB','#1a4a2a',84,0,NULL,NULL,'2 hours ago',NULL,'["Bispecific & Multispecific Antibody Manufacturing","ADC Development & GMP Manufacture","Cell & Gene Therapy CDMO","EMA, PMDA & Health Canada Inspected"]','["asia","taiwan","asia-pacific","global","eu","europe"]','["Hsinchu County, Taiwan"]'); -- Mycenax Biotech -> Mycenax Biotech
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (56,2774,'CDMO · Biologics & ADC Manufacturing','LB','#1a4a4a',82,0,NULL,NULL,'2 hours ago',NULL,'["Biologics & mAb Manufacturing","ADC & Bioconjugation Services","Biopharmaceutical Process Development","Lotte Group $2B Healthcare Investment"]','["asia","south korea","korea","seoul","global"]','["Seoul, South Korea"]'); -- Lotte Biologics -> Lotte Biologics
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (59,572,'Specialty Pharma · Generics, Biosimilars & Licensing','JP','#1a3a5a',79,0,NULL,NULL,'2 hours ago','seeker','["Branded & Complex Generics In-Licensing","Biosimilars & Super-Generics","Canadian Market Access & Licensing","Injectable & Specialty Pharmaceutical Products"]','["canada","north america","americas","ontario","mississauga","global"]','["Mississauga, Ontario, Canada"]'); -- Juno Pharmaceuticals Canada -> Juno Pharmaceuticals Canada
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (60,1033,'Specialty Pharma · Injectable & Ophthalmic Drug Repositioning','NV','#2a1a4a',78,0,NULL,NULL,'2 hours ago','seeker','["Injectable Drug Repositioning & 505(b)(2)","Ophthalmic Formulation Development","Unmet Clinical Need Specialty Injectables","FDA-Approved Molecule Enhancement Pipeline"]','["usa","united states","america","new jersey","bridgewater","global"]','["Bridgewater, New Jersey, USA"]'); -- Nevakar -> Nevakar
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (61,636,'Specialty Pharma · Global Generics & Licensing Network','AL','#1a2a5a',82,0,NULL,NULL,'2 hours ago','seeker','["Global Generic Formulations Licensing","Differentiated Generic & Biosimilar Products","Smart Collaboration & Partner Network","In-Licensing & Out-Licensing Generics"]','["europe","malta","eu","global","mena","africa","asia"]','["San Gwann, Malta"]'); -- Adalvo -> Adalvo
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (64,1162,'TechBio · Micellar Oncology Drug Delivery Platform','VV','#3a1a4a',77,0,NULL,NULL,'2 hours ago','seeker','["Micellar Drug Delivery for Oncology","Cantrixil (Blood Cancer) Pipeline","Docetaxel Micellar (Prostate Cancer) Pipeline","Veterinary Oncology (Paccal Vet)"]','["europe","sweden","nordic","scandinavia","solna","global"]','["Solna, Sweden"]'); -- Vivesto -> Vivesto
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (65,2886,'CDMO · Broad Dosage Form & Specialist Manufacturing','NP','#2a1a3a',85,0,NULL,NULL,'2 hours ago',NULL,'["Cytotoxic, Controlled Substance & Narcotic Manufacture","Sterile, Ophthalmic & Liposomal Formulations","Penicillin, Cephalosporin & Hormone Products","Solid Dose, Modified Release & Paediatric"]','["europe","uk","united kingdom","england","london","global"]','["London, UK · Multiple European sites"]'); -- NextPharma -> NextPharma
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (68,3498,'TechBio · Cell Engineering & Intracellular Delivery','AV','#1a3a4a',84,0,NULL,NULL,'2 hours ago','seeker','["Vector-Free Intracellular Delivery Platform","mRNA, Protein & Gene Editing Delivery","T Cell & Immune Cell Engineering","Cell Therapy Manufacturing Enablement"]','["ireland","europe","eu","kildare","maynooth","global"]','["Maynooth, Co. Kildare, Ireland"]'); -- Avectas -> Avectas
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (69,846,'TechBio · Cell Therapy Activation & Expansion Platform','BW','#1a2a5a',82,0,NULL,NULL,'2 hours ago','seeker','["Synecta Cell Therapy Activation & Expansion","CAR-T & T Cell Manufacturing Platform","Bioprocess Development for Cell Therapies","Cost-Reduction & Scalability Solutions"]','["usa","united states","pennsylvania","philadelphia","global"]','["Philadelphia, PA, USA"]'); -- BlueWhale Bio -> BlueWhale Bio
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (70,845,'Biopharma · Biosimilars, Biodefense & Novel Biologics','BF','#2a3a1a',83,0,NULL,NULL,'2 hours ago','seeker','["StableFast NS0 Biomanufacturing Platform","Biosimilar Development & Manufacturing","Biodefense Medical Countermeasures","CHO & NS0 Expression Systems"]','["usa","united states","maryland","frederick","global"]','["Frederick, Maryland, USA"]'); -- BioFactura -> BioFactura
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (71,844,'TechBio · Covalent Biologics Drug Discovery Platform','EN','#3a1a4a',85,0,NULL,NULL,'2 hours ago','seeker','["War-Lock Covalent Biologic Technology","Irreversible Target Binding Platform","Synthetic Biology & Proprietary Amino Acids","Out-Licensing & Co-Development Opportunities"]','["usa","united states","global"]','["USA"]'); -- Enlaza Therapeutics -> Enlaza Therapeutics
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (72,884,'TechBio · Ionizable Lipid & LNP Technology Licensing','CT','#4a2a1a',86,0,NULL,NULL,'2 hours ago','seeker','["Proprietary Ionizable Lipid Library","LNP Composition & RNA Sequence Design","Oligonucleotide Design & GMP Production","Lipid Nanoparticle Technology Licensing"]','["spain","europe","eu","zaragoza","global"]','["San Mateo de Gallego, Zaragoza, Spain"]'); -- Certest Biotec -> Certest Biotec
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (73,305,'CDMO · Lipid Chemistry & Emulsion Technology','LS','#1a4a3a',80,0,NULL,NULL,'2 hours ago','seeker','["45+ Years Lipid Chemistry Expertise","Emulsion Development for Oral & IV Nutrition","Drug Delivery Lipid Systems","Liposome & Lipid Emulsion Manufacturing"]','["sweden","europe","eu","norberg","scandinavia","global"]','["Norberg, Sweden"]'); -- Lipid Systems -> Lipid Systems
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (74,3329,'AI Platform · Personalised AI Models & NLP','YA','#1a2a4a',80,0,NULL,NULL,'2 hours ago','seeker','["Custom AI Model Creation from Company Data","Natural Language Processing (NLP) Platform","Customer Service, Analytics & Drug Discovery AI","Personalised AI for Life Science Applications"]','["canada","north america","toronto","global"]','["Toronto, Canada"]'); -- Younet AI -> Younet AI
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (75,2202,'AI Platform · Machine Learning Drug Discovery','AM','#2a1a4a',83,0,NULL,NULL,'2 hours ago','seeker','["ML & Synthetic Biology Drug Discovery","Novel Biologic & Nutraceutical Candidate Discovery","In Silico & In Vitro Hybrid Platform","Cancer, MDR Infections & Metabolic Disease Focus"]','["uk","united kingdom","northern ireland","belfast","europe","global"]','["Belfast, Northern Ireland, UK"]'); -- Amply Discovery -> Amply Discovery
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (76,27,'AI Platform · AI-Powered Drug Design Platform','GX','#3a1a2a',82,0,NULL,NULL,'2 hours ago','seeker','["AI, Physics & Chemistry Integrated Drug Design","Protein Structure & Interaction Prediction","Novel Therapeutics for Rare & Incurable Diseases","CASP & CAPRI Competition-Proven Technology"]','["korea","south korea","asia","seoul","global"]','["Seoul, South Korea"]'); -- Galux -> Galux
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (77,2526,'HealthTech · AI-Powered Clinical Trial Digital Solutions','EV','#1a3a5a',85,0,NULL,NULL,'2 hours ago','seeker','["AI-Powered Clinical Trial Management","Digital Solutions for Sponsors, Sites & Patients","Accelerated Clinical Study Timelines","300+ Person Global HealthTech Team"]','["switzerland","europe","eu","global"]','["Baar, Switzerland"]'); -- Evinova -> Evinova
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (78,2686,'AI Biopharma · Machine Learning Drug Discovery & Development','IS','#2a4a1a',88,0,NULL,NULL,'2 hours ago','seeker','["ML-Driven Drug Discovery Platform","Human Genetics & Functional Genomics","High-Throughput Biology & Disease Modelling","Obesity, Neurodegeneration & Rare Disease Focus"]','["usa","united states","california","san francisco","global"]','["San Francisco, California, USA"]'); -- insitro -> insitro
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (81,3124,'Primary Packaging · Safety Devices & Drug Delivery Systems','RO','#3a2a1a',78,0,NULL,NULL,'2 hours ago','provider','["SafeR Needle-Stick Injury Prevention Devices","Primary Pharmaceutical Packaging","Medical Device Drug Delivery Systems","Safety Packaging Solutions"]','["italy","europe","eu","global"]','["Castel Mella, Brescia, Italy"]'); -- Roncadelle -> Roncadelle Operations
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (88,3164,'Primary Packaging · Medical Devices & Drug Delivery Systems','SM','#1a3a4a',80,0,NULL,NULL,'2 hours ago','provider','["Medical Device & Drug Delivery System Design & Manufacture","High-End Primary Pharmaceutical Packaging","International Group Pharma Consumables","Drug Delivery Device France"]','["france","europe","eu","global"]','["Saint-Marcellin, France"]'); -- SGH Medical Pharma -> SGH medical pharma
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (89,1155,'TechBio · Transdermal Vaccine & Biologic Delivery Platform','VX','#2a4a1a',82,0,NULL,NULL,'2 hours ago','seeker','["MIMIX Transdermal Patch Platform for Vaccines","Needle-Free Painless Biologic Delivery","Out-Licensing & Co-Development Available","Vaccine & Biologic Transdermal Technology"]','["usa","united states","global"]','["USA"]'); -- Vaxess Technologies -> Vaxess Technologies
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (90,1004,'TechBio · Subcutaneous Biologic Drug Delivery Platform','LB','#1a3a5a',81,0,NULL,NULL,'2 hours ago','seeker','["Microglassification Protein Stabilisation Technology","Subcutaneous Biologic Delivery","Stable Dry-State Protein Microbeads","Co-Development Biologics Drug Delivery"]','["usa","united states","global"]','["USA"]'); -- Lindy Biosciences -> Lindy Biosciences
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (91,1003,'TechBio · Microencapsulation & Cell Therapy Delivery Platform','LK','#3a2a1a',80,0,NULL,NULL,'2 hours ago','seeker','["Microencapsulation of Biological Therapies","Controlled Release Cell Therapy Delivery","Tailored Microparticle Drug & Cell Release","Co-Development Cell & Biologic Delivery"]','["usa","united states","global"]','["USA"]'); -- Likarda -> Likarda
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (92,618,'CDMO · Controlled Release Drug Delivery Technology','BP','#1a2a4a',79,0,NULL,NULL,'2 hours ago','seeker','["MMCR Multi-Layer Micro-Particle Controlled Release","Controlled Release Syrup Technology","Out-Licensing & Co-Development Available","Oral Controlled Release Drug Delivery Belgium"]','["belgium","europe","eu","global"]','["Belgium, Europe"]'); -- BePharBel Manufacturing -> BePharBel Manufacturing
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (93,883,'Excipients & Drug Delivery · EVA Controlled Release Copolymers','CE','#4a2a2a',83,0,NULL,NULL,'2 hours ago','seeker','["VitalDose EVA Pharmaceutical Copolymers","Subcutaneous & Ophthalmic Implants Technology","Intravaginal Drug Delivery Systems","Controlled Release Excipient Licensing"]','["germany","europe","eu","usa","global"]','["Germany, Europe · Global"]'); -- Celanese -> Celanese
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (94,1126,'TechBio · Sustained Release Epidural Drug Delivery Platform','SP','#2a1a4a',80,0,NULL,NULL,'2 hours ago','seeker','["Sustained Release Micro-Suspension Epidural Technology","Spinal Pain Management Drug Delivery","Epidural Steroid Injection Improvement Platform","Out-Licensing & Co-Development Available"]','["usa","united states","global"]','["USA"]'); -- Spinethera -> Spinethera
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (96,12,'CDMO · Integrated Drug Development & Manufacturing','CA','#2a1a3a',90,0,NULL,NULL,'2 hours ago','provider','["Sterile Injectable Fill-Finish Manufacturing","Drug Product CDMO Biologics & Small Molecule","Clinical & Commercial Manufacturing","Oral Dose Softgel & Modified Release"]','["usa","united states","new jersey","somerset","europe","global"]','["Somerset, NJ, USA · Global"]'); -- Catalent -> Catalent Pharma Solutions
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (97,2569,'CRDMO · Integrated Drug Development CRO & CDMO','FL','#1a4a2a',84,0,NULL,NULL,'2 hours ago','provider','["Sterile Injectable & Aseptic Fill-Finish","Generic ANDA & NDA Formulation Development","Full-Spectrum CRDMO Drug Discovery to Commercial","Bioanalytical & Clinical CRO Services"]','["usa","united states","pennsylvania","exton","china","global"]','["Exton, Pennsylvania, USA · Global"]'); -- Frontage Laboratories -> Frontage Laboratories
INSERT INTO featured_id_map (cos_id,company_id,type,logo,color,score,alerts,alert_url,alert_info,upd,partner_type,caps,regions,sites) VALUES (98,1908,'CDMO · Sterile Injectable & Nasal Spray Specialist','RP','#3a2a1a',82,0,NULL,NULL,'2 hours ago','provider','["Aseptic Vial Fill-Finish Development & Manufacturing","Nasal Spray Development & Manufacturing","Generic Sterile Injectable ANDA Development","DEA Schedule I-V Sterile Products"]','["usa","united states","new jersey","lakewood","north america"]','["Lakewood, New Jersey, USA"]'); -- Renaissance Pharma -> Renaissance Pharma
